var tableauQuestion = [
    {   question : "Daca conduci cu 80 km/h si te aproprii de o zona rezidentiala, inseamna ca:",
        propositionA : "O sa cresti viteza",
        propositionB : "Poti sa mergi cu viteza atata timp cat nu sunt masini",
        propositionC : "Va trebuii sa incetinesti",
        propositionD : "Poti sa-ti mentii viteza",
        reponse : "C"},
		
    {   question : "In timp ce faci stanga la un semafor verde, vezi ca un pieton trece strada pe zebra. Cine are prioritate?",
        propositionA : "Pietonul, deoarece ei pot trece pe orice culoare a semaforului",
        propositionB : "Vehiculul tau deoarece ai trecut pe verde",
        propositionC : "Pietonul, deoarece trece pe verde",
        propositionD : "Vehiculul tau, deoarece automobilele au mereu prioritate",
        reponse : "C"},
		
    {   question : "Daca nu se indica, viteza maxima in zonele rezidentiale este de:",
        propositionA : "50km",
        propositionB : "55km",
        propositionC : "65km",
        propositionD : "70km",
        reponse : "A"},
	
	{   question : "Inainte de schimbarea benzii, trebuie sa:",
        propositionA : "Iti verific oglinzile",
        propositionB : "Verifici unghiul mort",
        propositionC : "Semnaleaza-ti intentiile",
        propositionD : "Toate cele de mai sus",
        reponse : "D"},
		
	{   question : "Care este nivelul maxim admis de alcool in sange?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},
		
	{   question : "Trebuie sa tragi pe dreapta si sa astepti pana vehiculul de urgente a trecut, facand exceptie:",
        propositionA : "Esti grabit",
        propositionB : "Nu este destul loc pentru automobil pe o alta banda",
        propositionC : "Esti intr-o zona ce indica scoala",
        propositionD : "Esti intr-o intersectie",
        reponse : "D"},
	
	{   question : "Pe o autostrada cu 3 benzi s-a blocat circulatia. Pe unde vor circula vehiculele de urgenta?",
        propositionA : "Pe banda de urgenta",
        propositionB : "Intre banda din stanga si banda din mijloc",
        propositionC : "Intre banda din dreapta si banda din mijloc",
        propositionD : "Oriunde",
        reponse : "A"},
		
	{   question : "Care este regula prioritatii de trecere la intersectia a doua drumuri de aceeasi categorie?",
        propositionA : "Prioritatea de dreapta",
        propositionB : "Prioritatea primului sosit",
        propositionC : "Prioritatea de drum principal",
        propositionD : "Nu conteaza",
        reponse : "A"},
		
	{   question : "Care autovehicule pot fi echipate cu lumini speciale de avertizare de culoare albastra",
        propositionA : "Legea nu prevede",
        propositionB : "Orice vehicul pentru care se obtine aprobarea politiei rutiere",
        propositionC : "Vehiculele apartinand politiei, jandarmeriei si politiei de frontiera",
        propositionD : "Oricare.",
        reponse : "C"},
		
	{   question : "Cand esti depasit de un alt vehicul este important sa nu:",
        propositionA : "Incetinesti",
        propositionB : "Verifici oglinzile",
        propositionC : "Sa te uiti la celalalt conducator",
        propositionD : "Sa accelerezi",
        reponse : "D"},
]
